# Generated by Django 3.0.3 on 2020-05-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangojob',
            options={'ordering': ('next_run_time',), 'verbose_name': '计划任务', 'verbose_name_plural': '计划任务'},
        ),
        migrations.AlterModelOptions(
            name='djangojobexecution',
            options={'ordering': ('-run_time',), 'verbose_name': '执行记录', 'verbose_name_plural': '执行记录'},
        ),
    ]
