# Generated by Django 3.0.3 on 2020-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signtasks',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
    ]
