# Generated by Django 3.0.3 on 2020-05-03 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='电话号码'),
        ),
        migrations.CreateModel(
            name='SignRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_time', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('sign_active', models.BooleanField(verbose_name='打卡状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sign_time'],
            },
        ),
    ]
