# Generated by Django 3.0.3 on 2020-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signrecord',
            options={'ordering': ['-sign_time'], 'verbose_name': '签到记录', 'verbose_name_plural': '签到记录'},
        ),
        migrations.AddField(
            model_name='user',
            name='wxPushKey',
            field=models.CharField(max_length=50, null=True, verbose_name='消息Key'),
        ),
    ]
