# Generated by Django 3.0.3 on 2020-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200509_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wxPushKey',
            field=models.CharField(default='', max_length=50, verbose_name='消息Key'),
        ),
    ]
