# Generated by Django 3.0.3 on 2020-05-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200503_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signrecord',
            name='sign_active',
            field=models.BooleanField(default=True, verbose_name='打卡状态'),
        ),
    ]
