# Generated by Django 3.0.3 on 2020-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200509_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie_expired_time',
            field=models.DateTimeField(null=True, verbose_name='cookie失效时间'),
        ),
    ]
